### ISSUE TITLE
Installation error on linux UBUNTU 20.04

### ISSUE THREAD

**Issue by mrahmadusama** [msaaddev/geo-location-cli#2]
**Describe the bug**
Unable to install through linux terminal

**Screenshots**
![image](https://user-images.githubusercontent.com/48976847/85819334-ccf2f380-b78c-11ea-862f-1d37b4c2f3e4.png)

**Desktop (please complete the following information):**
 - OS: POP! OS based on Ubuntu 20.04

**Comment by msaaddev** [comment]
Install it as admin. Try `sudo npm i -g geo-location-cli`

**Comment by msaaddev** [comment]
@IahmadDev has your problem been resolved?

**Comment by mrahmadusama** [comment]
> @IahmadDev has your problem been resolved?

YES! Thank you very much.
